services:
  # Backend Service
  backend:
    build:
      context: ./service
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./service:/app
      - /app/node_modules
    networks:
      - vegas-slot-network
    depends_on: []

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_API_URL=http://localhost:4000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vegas-slot-network
    depends_on:
      - backend

networks:
  vegas-slot-network:
    driver: bridge
